import it.icon.cornercoffe.pojo.*;
import java.util.*;
import java.lang.*;

global it.icon.cornercoffe.pojo.CoffeeChoose coffeeChoose;  

rule "Rules Giava"
	salience 100
	when $coffee:CoffeeType(body >= 90 , bitter >= 80,  acidity < 20, aroma <= 40, sweetness <= 50)
	then coffeeChoose.setCoffee("Giava");
end

rule "Rules India"
	salience 100
	when $coffee:CoffeeType(body >= 60 , bitter >= 80, acidity < 30, aroma <= 40, sweetness <= 50)
	then coffeeChoose.setCoffee("India");
end

rule "Rules Brazil"
	salience 100
	when $coffee:CoffeeType(body >= 50 , bitter >= 50, acidity < 50, aroma <= 50, sweetness > 50)
	then coffeeChoose.setCoffee("Brazil");
end

rule "Rules Mexico"
	salience 100
	when $coffee:CoffeeType(body < 50, bitter < 50, acidity >= 50, aroma > 50, sweetness > 50)
	then coffeeChoose.setCoffee("Mexico");
end

rule "Rules Kenya"
	salience 100
	when $coffee:CoffeeType(body < 50, bitter < 50, acidity >= 70, aroma > 70, sweetness > 60)
	then coffeeChoose.setCoffee("Kenya");
end

rule "Rules Honduras"
	salience 100
	when $coffee:CoffeeType(body < 50, bitter < 50, acidity >= 50, aroma > 50, sweetness <= 50)
	then coffeeChoose.setCoffee("Honduras");
end

rule "Rules Etiopia"
	salience 100
	when $coffee:CoffeeType(body < 30, bitter < 50, acidity >= 80, aroma > 80, sweetness <= 40)
	then coffeeChoose.setCoffee("Etiopia");
end

rule "Rules Arabica Percentage"
	salience 10
	when $coffee:CoffeeType(body < 50, bitter < 50, acidity > 50, aroma > 50)
	then coffeeChoose.moreArabica(10);
end

rule "Rules Robusta Percentage"
	salience 10
	when $coffee:CoffeeType(body >= 50, bitter >= 50, acidity <= 50, aroma <= 50)
	then coffeeChoose.moreRobusta(10);
end